### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Cassarah** [Undertone0809/arduino-uno-dev#20]
![image](https://user-images.githubusercontent.com/117179247/201511220-95a95ab5-c95b-46f5-8330-6224ec2ac179.png)

**Comment by Cassarah** [comment]
韩雨霖

**Comment by Undertone0809** [comment]
fine，也算完成吧。
![image](https://user-images.githubusercontent.com/72488598/201511369-e5004247-a025-427e-9c5c-e20411ace990.png)
