### ISSUE TITLE
enhance: PWM介绍过于简单

### ISSUE THREAD

**Issue by Undertone0809** [Undertone0809/arduino-uno-dev#9]
关于PWM的介绍过于简略，直接以外链的方式跳转了，是否可以用通俗易懂的话介绍一下PWM? 此外，demo的形式也比较少比较简单，是否可以增加一些新的PWM demo？

![image](https://user-images.githubusercontent.com/72488598/199570962-279617ad-a92e-48ab-8b5f-aabe07f2035f.png)

**Comment by wpjNB** [comment]
pwm简称脉冲宽度调制，即在一周期内存在不同极性电平状态（http://t.csdn.cn/LcUCQ
）

**Comment by pinduangduang** [comment]
PWM全称Pulse Width Modulation：脉冲宽度调制（简称脉宽调制，通俗的讲就是调节脉冲的宽度），是电子电力应用中非常重要的一种控制技术，PWM波是在这种技术手段控制下的脉冲波。(https://zhuanlan.zhihu.com/p/375002847
)

**Comment by wpjNB** [comment]
surprise


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月7日(周一) 上午9:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Undertone0809/arduino-uno-dev] enhance: PWM介绍过于简单 (Issue #9)




 
PWM全称Pulse Width Modulation：脉冲宽度调制（简称脉宽调制，通俗的讲就是调节脉冲的宽度），是电子电力应用中非常重要的一种控制技术，PWM波是在这种技术手段控制下的脉冲波。(https://zhuanlan.zhihu.com/p/375002847
 )
 
&mdash;

**Comment by Undertone0809** [comment]
You guys may not understand what I mean. This issue need to you change the markdown file then create a pull request. @wpjNB @pinduangduang

**Comment by wpjNB** [comment]
学长英语不错哈

**Comment by pinduangduang** [comment]
OK,let me think about it again.

**Comment by Undertone0809** [comment]
@Reisen-C has solve the problem. You can use it as a reference. @wpjNB @pinduangduang

**Comment by Undertone0809** [comment]
Does someone can solve this problem and new a pull request? @wpjNB @pinduangduang 
![image](https://user-images.githubusercontent.com/72488598/201274459-a3e445c0-e23d-4f91-99ac-426777117605.png)
